version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2
  browser-tools: circleci/browser-tools@1.0.1

jobs:
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7-node
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          BUNDLE_PATH: vendor/bundle
          DATABASE_URL: "mysql2://root:password@127.0.0.1/circle_test"
          RAILS_ENV: test
      - image: circleci/mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: password
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test
      - run:
          name: run rubocop checking
          command: bundle exec rubocop
