module CustomData
  class Songs
    def self.post_data_to_db
      data.each do |json|
        json_composer = json[:composer]
        composer = Composer.find_or_create_by(name: json_composer[:name].downcase)

        json_composition = json[:composition]
        composition = Composition.find_or_create_by(name: json_composition[:name].downcase)

        json_songs = json[:songs]
        json_songs.each do |json_song|
          Song.find_or_create_by(
            composer_id: composer.id,
            composition_id: composition.id,
            title: json_song[:title],
          )
        end
      end
    end

    def self.data
      [
        {
          composer: {
            name: "Bach",
          },
          composition: {
            name: "Brandenburg Concerto",
          },
          songs: [
            { title: "no. 1, BWV 1046, F major" },
            { title: "no. 2, BWV 1047, F major" },
            { title: "no. 3, BWV 1048, G major" },
            { title: "no. 4, BWV 1049, G major" },
            { title: "no. 5, BWV 1050, D major" },
            { title: "no. 6, BWV 1051, B Flat major" },
          ],
        },
        {
          composer: {
            name: "Bach",
          },
          composition: {
            name: "Concerto",
          },
          songs: [
            { title: "Harpsichord, Flute, Violin and Orchestra, BWV 1044, A minor" },
            { title: "Two Harpsichords and Orchestra, BWV1060, C minor" },
            { title: "Two Violins and Orchestra, BWV 1043, D minor" },
            { title: "Violin and Orchestra, BWV 1041, A minor" },
            { title: "Violin, Oboe and Orchestra, BWV 1060, D minor" },
            { title: "Harpsichord and Orchestra no. 1, BWV 1052, D minor" },
            { title: "Three Harpsichords and Orchestra no. 1, BWV 1063, D minor" },
            { title: "Two Harpsichords and Orchestra no. 1, BWV 1061, C major" },
            { title: "Violin and Orchestra no. 1, BWV 1041, A minor" },
            { title: "Three Harpsichords and Orchestra no. 2, BWV 1064, C major" },
            { title: "Two Harpsichords and Orchestra no. 2, BWV 1062, C minor" },
            { title: "Violin and Orchestra no. 2, BWV 1042, E major" },
            { title: "Harpsichord and Orchestra no. 3, BWV 1054, D major" },
            { title: "Four Harpsichords and Orchestra no. 4, BWV 1065, A minor" },
            { title: "Harpsichord and Orchestra no. 4, BWV 1055, A major" },
            { title: "Harpsichord and Orchestra no. 5, BWV 1056, F minor" },
            { title: "Harpsichord and Orchestra no. 7, BWV 1058, G minor" },
          ],
        },
        {
          composer: {
            name: "Bach",
          },
          composition: {
            name: "Suite",
          },
          songs: [
            { title: "Orchestra no. 1, BWV 1066, C major" },
            { title: "Orchestra no. 2, BWV 1067, B minor" },
            { title: "Orchestra no. 3, BWV 1068, D major" },
            { title: "Orchestra no. 4, BWV 1069, D major" },
          ],
        },
        {
          composer: {
            name: "Bach",
          },
          composition: {
            name: "Ballet",
          },
          songs: [
            { title: "2 and 3 Part Inventions" },
            { title: "Brandenburg" },
            { title: "Concerto Barocco" },
            { title: "The Goldberg Variations" },
            { title: "In Memory Of ..." },
            { title: "Le jeune homme et la mort" },
            { title: "A Suite of Dances" },
            { title: "Tribute" },
            { title: "The Wise Virgins" },
          ],
        },
        {
          composer: {
            name: "Bach",
          },
          composition: {
            name: "Cantata",
          },
          songs: [
            { title: "Ach Gott, vom Himmel sieh darein, BWV 2" },
            { title: "Ach Gott, wie manches Herzeleid, BWV 3" },
            { title: "Ach Gott, wie manches Herzeleid, BWV 58" },
            { title: "Ach Herr, mich armen Sünder, BWV 135" },
            { title: "Ach! ich sehe, itzt, da ich zur Hochzeit gehe, BWV 162" },
            { title: "Ach wie flüchtig, ach wie nichtig, BWV 26" },
            { title: "Ach, lieben Christen, seid getrost, BWV 114" },
            { title: "Allein zu dir, Herr Jesu Christ, BWV 33" },
            { title: "Alles mit Gott und nichts ohn' ihn, BWV 1127" },
            { title: "Alles nur nach Gottes Willen, BWV 72" },
            { title: "Alles, was von Gott geboren, BWV 80a" },
            { title: "Also hat Gott die Welt geliebt, BWV 68" },
            { title: "Am Abend aber desselbigen Sabbats, BWV 42" },
            { title: "Ärgre dich, o Seele, nicht, BWV 186" },
            { title: "Auf Christi Himmelfahrt allein, BWV 128" },
            { title: "Aus der Tiefen rufe ich, Herr, zu dir, BWV 131" },
            { title: "Aus tiefer Not schrei ich zu dir, BWV 38" },
            { title: "Barmherziges Herze der ewigen Liebe, BWV 185" },
            { title: "Bekennen will ich seinen Namen, BWV 200" },
            { title: "Bereitet die Wege, bereitet die Bahn, BWV 132" },
            { title: "Bisher habt ihr nichts gebeten in meinem Namen, BWV 87" },
            { title: "Bleib bei uns, denn es will Abend werden, BWV 6" },
            { title: "Brich dem Hungrigen dein Brot, BWV 39" },
            { title: "Bringet dem Herrn Ehre seines Namens, BWV 148" },
            { title: "Christ lag in Todes Banden, BWV 4" },
            { title: "Christ unser Herr zum Jordan kam, BWV 7" },
            { title: "Christen, ätzet diesen Tag, BWV 63" },
            { title: "Christum wir sollen loben schon, BWV 121" },
            { title: "Christus, der ist mein Leben, BWV 95" },
            { title: "Darzu ist erschienen der Sohn Gottes, BWV 40" },
            { title: "Du Friedefürst, Herr Jesu Christ, BWV 116" },
            { title: "Du Hirte Israel, höre, BWV 104" },
            { title: "Du sollt Gott, deinen Herren, lieben, BWV 77" },
            { title: "Du wahrer Gott und Davids Sohn, BWV 23" },
            { title: "Ehre sei dir, Gott, gesungen, BWV 248 V" },
            { title: "Ehre sei Gott in der Höhe, BWV 197a" },
            { title: "Die Elenden sollen essen, BWV 75" },
            { title: "Er rufet seinen Schafen mit Namen, BWV 175" },
            { title: "Erforsche mich, Gott, und erfahre mein Herz, BWV 136" },
            { title: "Erfreut euch, ihr Herzen, BWV 66" },
            { title: "Erfreute Zeit im neuen Bunde, BWV 83" },
            { title: "Erhalt uns, Herr, bei deinem Wort, BWV 126" },
            { title: "Erhöhtes Fleisch und Blut, BWV 173" },
            { title: "Erschallet, ihr Lieder, erklinget, ihr Saiten! BWV 172" },
            { title: "Erwünschtes Freudenlicht, BWV 184" },
            { title: "Es erhub sich ein Streit, BWV 19" },
            { title: "Es ist das Heil uns kommen her, BWV 9" },
            { title: "Es ist dir gesagt, Mensch, was gut ist, BWV 45" },
            { title: "Es ist ein trotzig und verzagt Ding, BWV 176" },
            { title: "Es ist euch gut, daß ich hingehe, BWV 108" },
            { title: "Es ist nichts Gesundes an meinem Leibe, BWV 25" },
            { title: "Es reißet euch ein schrecklich Ende, BWV 90" },
            { title: "Es wartet alles auf dich, BWV 187" },
            { title: "Fallt mit Danken, fallt mit Loben, BWV 248 IV" },
            { title: "Falsche Welt, dir trau ich nicht, BWV 52" },
            { title: "Ein feste Burg ist unser Gott, BWV 80" },
            { title: "Freue dich, erlöste Schar, BWV 30" },
            { title: "Der Friede sei mit dir, BWV 158" },
            { title: "Geist und Seele wird verwirret, BWV 35" },
            { title: "Gelobet sei der Herr, mein Gott, BWV 129" },
            { title: "Gelobet seist du, Jesu Christ, BWV 91" },
            { title: "Dem Gerechten muß das Licht, BWV 195" },
            { title: "Gleichwie der Regen und Schnee vom Himmel fällt, BWV 18" },
            { title: "Gloria in excelsis Deo, BWV 191" },
            { title: "Gott der Herr ist Sonn und Schild, BWV 79" },
            { title: "Gott fähret auf mit Jauchzen, BWV 43" },
            { title: "Gott ist unsre Zuversicht, BWV 197" },
            { title: "Gott soll allein mein Herze haben, BWV 169" },
            { title: "Gott, man lobet dich in der Stille, BWV 120b" },
            { title: "Gott, wie dein Name, so ist auch dein Ruhm, BWV 171" },
            { title: "Gottes Zeit ist die allerbeste Zeit, BWV 106" },
            { title: "Gottlob! nun geht das Jahr zu Ende, BWV 28" },
            { title: "Halt im Gedächtnis Jesum Christ, BWV 67" },
            { title: "Herr Christ, der einge Gottessohn, BWV 96" },
            { title: "Der Herr denket an uns, BWV 196" },
            { title: "Herr Gott, Beherrscher aller Dinge, BWV 120a" },
            { title: "Herr Gott, dich loben alle wir, BWV 130" },
            { title: "Herr Gott, dich loben wir, BWV 16" },
            { title: "Der Herr ist mein getreuer Hirt, BWV 112" },
            { title: "Herr Jesu Christ, du höchstes Gut, BWV 113" },
            { title: "Herr Jesu Christ, wahr' Mensch und Gott, BWV 127" },
            { title: "Herr, deine Augen sehen nach dem Glauben, BWV 102" },
            { title: "Herr, gehe nicht ins Gericht mit deinem Knecht, BWV 105" },
            { title: "Herr, wenn die stolzen Feinde schnauben, BWV 248 VI" },
            { title: "Herr, wie du willt, so schicks mit mir, BWV 73" },
            { title: "Herrscher des Himmels, erhöre das Lallen, BWV 248 III" },
            { title: "Ein Herz, das seinen Jesum lebend weiß, BWV 134" },
            { title: "Herz und Mund und Tat und Leben, BWV 147" },
            { title: "Herz und Mund und Tat und Leben, BWV 147a" },
            { title: "Die Himmel erzählen die Ehre Gottes, BWV 76" },
            { title: "Der Himmel lacht! Die Erde jubilieret, BWV 31" },
            { title: "Himmelskönig, sei willkommen, BWV 182" },
            { title: "Höchsterwünschtes Freudenfest, BWV 194" },
            { title: "Ich armer Mensch, ich Sündenknecht, BWV 55" },
            { title: "Ich bin ein guter Hirt, BWV 85" },
            { title: "Ich bin vergnügt mit meinem Glücke, BWV 84" },
            { title: "Ich elender Mensch, wer wird mich erlösen, BWV 48" },
            { title: "Ich freue mich in dir, BWV 133" },
            { title: "Ich geh und suche mit Verlangen, BWV 49" },
            { title: "Ich glaube, lieber Herr, hilf meinem Unglauben, BWV 109" },
            { title: "Ich hab in Gottes Herz und Sinn, BWV 92" },
            { title: "Ich habe genug, BWV 82" },
            { title: "Ich habe meine Zuversicht, BWV 188" },
            { title: "Ich hatte viel Bekümmernis, BWV 21" },
            { title: "Ich lasse dich nicht, du segnest mich denn, BWV 157" },
            { title: "Ich lebe, mein Herze, zu deinem Ergötzen, BWV 145" },
            { title: "Ich liebe den Höchsten von ganzem Gemüte, BWV 174" },
            { title: "Ich ruf zu dir, Herr Jesu Christ, BWV 177" },
            { title: "Ich steh mit einem Fuß im Grabe, BWV 156" },
            { title: "Ich will den Kreuzstab gerne tragen, BWV 56" },
            { title: "Ihr Menschen, rühmet Gottes Liebe, BWV 167" },
            { title: "Ihr werdet weinen und heulen, BWV 103" },
            { title: "Ihr, die ihr euch von Christo nennet, BWV 164" },
            { title: "In allen meinen Taten, BWV 97" },
            { title: "Jauchzet Gott in allen Landen, BWV 51" },
            { title: "Jauchzet, frohlocket! Auf, preiset die Tage, BWV 248 I" },
            { title: "Jesu, der du meine Seele, BWV 78" },
            { title: "Jesu, nun sei gepreiset, BWV 41" },
            { title: "Jesus nahm zu sich die Zwölfe, BWV 22" },
            { title: "Jesus schläft, was soll ich hoffen? BWV 81" },
            { title: "Klagt, Kinder, klagt es aller Welt, BWV 244a" },
            { title: "Komm, du süße Todesstunde, BWV 161" },
            { title: "Leichtgesinnte Flattergeister, BWV 181" },
            { title: "Liebster Gott, wenn werd ich sterben? BWV 8" },
            { title: "Liebster Immanuel, Herzog der Frommen, BWV 123" },
            { title: "Liebster Jesu, mein Verlangen, BWV 32" },
            { title: "Lobe den Herren, den mächtigen König der Ehren, BWV 137" },
            { title: "Lobe den Herrn, meine Seele, BWV 69a" },
            { title: "Lobe den Herrn, meine Seele, BWV 143" },
            { title: "Lobet den Herrn, alle seine Heerscharen, BWV Anh. 5" },
            { title: "Mache dich, mein Geist, bereit, BWV 115" },
            { title: "Man singet mit Freuden vom Sieg, BWV 149" },
            { title: "Mein Gott, wie lang, ach lange? BWV 155" },
            { title: "Mein Herze schwimmt im Blut, BWV 199" },
            { title: "Mein liebster Jesus ist verloren, BWV 154" },
            { title: "Meine Seel erhebt den Herren, BWV 10" },
            { title: "Meine Seele soll Gott loben, BWV 223" },
            { title: "Meine Seufzer, meine Tränen, BWV 13" },
            { title: "Meinen Jesum laß ich nicht, BWV 124" },
            { title: "Mit Fried und Freud ich fahr dahin, BWV 125" },
            { title: "Nach dir, Herr, verlanget mich, BWV 150" },
            { title: "Das neugeborne Kindelein, BWV 122" },
            { title: "Nimm von uns, Herr, du treuer Gott, BWV 101" },
            { title: "Nimm, was dein ist, und gehe hin, BWV 144" },
            { title: "Nun danket alle Gott, BWV 192" },
            { title: "Nun ist das Heil und die Kraft, BWV 50" },
            { title: "Nun komm, der Heiden Heiland, BWV 61" },
            { title: "Nun komm, der Heiden Heiland, BWV 62" },
            { title: "Nur jedem das Seine, BWV 163" },
            { title: "O ewiges Feuer, o Ursprung der Liebe, BWV 34a" },
            { title: "O ewiges Feuer, o Ursprung der Liebe, BWV 34" },
            { title: "O Ewigkeit, du Donnerwort, BWV 60" },
            { title: "O Ewigkeit, du Donnerwort, BWV 20" },
            { title: "O heilges Geist- und Wasserbad, BWV 165" },
            { title: "Schau, lieber Gott, wie meine Feind, BWV 153" },
            { title: "Schauet doch und sehet, ob irgend ein Schmerz sei, BWV 46" },
            { title: "Schmücke dich, o liebe Seele, BWV 180" },
            { title: "Schwingt freudig euch empor, BWV 36" },
            { title: "Sehet, welch eine Liebe hat uns der Vater erzeiget, BWV 64" },
            { title: "Sehet, wir gehn hinauf gen Jerusalem, BWV 159" },
            { title: "Sei Lob und Ehr dem höchsten Gut, BWV 117" },
            { title: "Selig ist der Mann, BWV 57" },
            { title: "Sie werden aus Saba alle kommen, BWV 65" },
            { title: "Sie werden euch in den Bann tun, BWV 44" },
            { title: "Sie werden euch in den Bann tun, BWV 183" },
            { title: "Siehe zu, daß deine Gottesfurcht nicht Heuchelei sei, BWV 179" },
            { title: "Siehe, ich will viel Fischer aussenden, BWV 88" },
            { title: "Singet dem Herrn ein neues Lied, BWV 190" },
            { title: "Singet dem Herrn ein neues Lied, BWV 190a" },
            { title: "Süßer Trost, mein Jesus kömmt, BWV 151" },
            { title: "Tilge, Höchster, meine Sünden, BWV 1083" },
            { title: "Tritt auf die Glaubensbahn, BWV 152" },
            { title: "Tue Rechnung! Donnerwort, BWV 168" },
            { title: "Und es waren Hirten in derselben Gegend, BWV 248 II" },
            { title: "Ein ungefärbt Gemüte, BWV 24" },
            { title: "Unser Mund sei voll Lachens, BWV 110" },
            { title: "Vergnügte Ruh, beliebte Seelenlust, BWV 170" },
            { title: "Wachet auf, ruft uns die Stimme, BWV 140" },
            { title: "Wachet! betet! betet! wachet! BWV 70" },
            { title: "Wahrlich, wahrlich, ich sage euch, BWV 86" },
            { title: "Wär Gott nicht mit uns diese Zeit, BWV 14" },
            { title: "Warum betrübst du dich, mein Herz, BWV 138" },
            { title: "Was frag ich nach der Welt, BWV 94" },
            { title: "Was Gott tut, das ist wohlgetan, BWV 98" },
            { title: "Was Gott tut, das ist wohlgetan, BWV 99" },
            { title: "Was Gott tut, das ist wohlgetan, BWV 100" },
            { title: "Was mein Gott will, das g'scheh allzeit, BWV 111" },
            { title: "Was soll ich aus dir machen, Ephraim, BWV 89" },
            { title: "Was willst du dich betrüben, BWV 107" },
            { title: "Weinen, Klagen, Sorgen, Zagen, BWV 12" },
            { title: "Wer da gläubet und getauft wird, BWV 37" },
            { title: "Wer Dank opfert, der preiset mich, BWV 17" },
            { title: "Wer mich liebet, der wird mein Wort halten, BWV 59" },
            { title: "Wer mich liebet, der wird mein Wort halten, BWV 74" },
            { title: "Wer nur den lieben Gott läßt walten, BWV 93" },
            { title: "Wer sich selbst erhöhet, der soll erniedriget werden, BWV 47" },
          ],
        },
        {
          composer: {
            name: "Bach",
          },
          composition: {
            name: "Fugue",
          },
          songs: [
            { title: "The Art of Fugue" },
            { title: "Chromatic Fantasia and Fugue" },
            { title: "Clavier-Übung III" },
            { title: "Fantasia and Fugue in C minor, BWV 537" },
            { title: "Fantasia and Fugue in C minor, BWV 562" },
            { title: "Fantasia and Fugue in C minor, BWV 906" },
            { title: "Great Fantasia and Fugue in G minor, BWV 542" },
            { title: "Fugue in G minor, BWV 131a" },
            { title: "Fugue in G minor, BWV 578" },
            { title: "Fugue in G minor, BWV 1000" },
            { title: "Passacaglia and Fugue in C minor, BWV 582" },
            { title: "Prelude (Toccata) and Fugue in E major, BWV 566" },
            { title: "Prelude and Fugue in A minor, BWV 543" },
            { title: "Prelude and Fugue in B minor, BWV 544" },
            { title: "Prelude and Fugue in C major, BWV 531" },
            { title: "Prelude and Fugue in C minor, BWV 546" },
            { title: "Prelude and Fugue in C minor, BWV 871" },
            { title: "Prelude and Fugue in D major, BWV 532" },
            { title: "Prelude and Fugue in E minor, BWV 548" },
            { title: "Prelude, Fugue and Allegro in E-flat major, BWV 998" },
            { title: "Toccata and Fugue in D minor, BWV 538" },
            { title: "Toccata and Fugue in D minor, BWV 565" },
            { title: "Toccata and Fugue in F major, BWV 540" },
            { title: "Toccata, Adagio and Fugue in C major, BWV 564" },
          ],
        },
        {
          composer: {
            name: "Beethoven",
          },
          composition: {
            name: "Sonata",
          },
          songs: [
            { title: "Cello No. 1" },
            { title: "Cello No. 2" },
            { title: "Cello No. 3" },
            { title: "Cello No. 4" },
            { title: "Cello No. 5" },
            { title: "Piano No. 1" },
            { title: "Piano No. 2" },
            { title: "Piano No. 3" },
            { title: "Piano No. 4" },
            { title: "Piano No. 5" },
            { title: "Piano No. 6" },
            { title: "Piano No. 7" },
            { title: "Piano No. 8" },
            { title: "Piano No. 9" },
            { title: "Piano No. 10" },
            { title: "Piano No. 11" },
            { title: "Piano No. 12" },
            { title: "Piano No. 13" },
            { title: "Piano No. 14" },
            { title: "Piano No. 15" },
            { title: "Piano No. 16" },
            { title: "Piano No. 17" },
            { title: "Piano No. 18" },
            { title: "Piano No. 19" },
            { title: "Piano No. 20" },
            { title: "Piano No. 21" },
            { title: "Piano No. 22" },
            { title: "Piano No. 23" },
            { title: "Piano No. 24" },
            { title: "Piano No. 25" },
            { title: "Piano No. 26" },
            { title: "Piano No. 27" },
            { title: "Piano No. 28" },
            { title: "Piano No. 29" },
            { title: "Piano No. 30" },
            { title: "Piano No. 31" },
            { title: "Piano No. 32" },
            { title: "Piano WoO. 51" },
            { title: "Piano No. 13" },
            { title: "Piano No. 14" },
            { title: "Three Piano Sonata WoO 47, no. 1, E flat major" },
            { title: "Three Piano Sonata WoO 47, no. 2, F minor" },
            { title: "Three Piano Sonata WoO 47, no. 3, D major" },
            { title: "Violin No. 1" },
            { title: "Violin No. 2" },
            { title: "Violin No. 3" },
            { title: "Violin No. 4" },
            { title: "Violin No. 5" },
            { title: "Violin No. 6" },
            { title: "Violin No. 7" },
            { title: "Violin No. 8" },
            { title: "Violin No. 9" },
            { title: "Violin No. 10" },
            { title: "Violin in A major" },
          ],
        },
        {
          composer: {
            name: "Beethoven",
          },
          composition: {
            name: "Concerto",
          },
          songs: [
            { title: "Piano and Orchestra, E flat major" },
            { title: "Piano, Violin, Cello and Orchestra, op. 56, C major" },
            { title: "Violin and Orchestra, op. 61, D major" },
            { title: "Piano and Orchestra no. 1, op. 15, C major" },
            { title: "Piano and Orchestra no. 2, op. 19, B flat major" },
            { title: "Piano and Orchestra no. 3, op. 37, C minor" },
            { title: "Piano and Orchestra no. 4, op. 58, G major" },
            { title: "Piano and Orchestra no. 5, op. 73, E flat (Emperor)" },
          ],
        },
        {
          composer: {
            name: "Beethoven",
          },
          composition: {
            name: "Grosse Fuge",
          },
          songs: [
            { title: "op. 133, B flat major" },
          ],
        },
        {
          composer: {
            name: "Beethoven",
          },
          composition: {
            name: "String Quartet",
          },
          songs: [
            { title: "no. 1, op. 18, no. 1, F major" },
            { title: "no. 2, op. 18, no. 2, G major" },
            { title: "no. 3, op. 18, no. 3, D major" },
            { title: "no. 4, op. 18, no. 4, C minor" },
            { title: "no. 5, op. 18, no. 5, A major" },
            { title: "no. 6, op. 18, no. 6, B flat major" },
            { title: "no. 7, op. 59, no. 1, F major" },
            { title: "no. 8, op. 59, no. 2, E minor" },
            { title: "no. 9, op. 59, no. 3, C major" },
            { title: "no. 10, op. 74, E flat major" },
            { title: "no. 11, op. 95, F minor" },
            { title: "no. 12, op. 127, E flat major" },
            { title: "no. 13, op. 130, B flat major" },
            { title: "no. 14, op. 131, C sharp minor" },
            { title: "no. 15, op. 132, A minor" },
            { title: "no. 16, op. 135, F major" },
          ],
        },
        {
          composer: {
            name: "Beethoven",
          },
          composition: {
            name: "Symphonie",
          },
          songs: [
            { title: "no. 1, op. 21, C major" },
            { title: "no. 2, op. 36, D major" },
            { title: "no. 3, op. 55, E flat major (Eroica)" },
            { title: "no. 4, op. 60, B flat major" },
            { title: "no. 5, op. 67, C minor" },
            { title: "no. 6, op. 68, F major (Pastoral)" },
            { title: "no. 7, op. 92, A major" },
            { title: "no. 8, op. 93, F major" },
            { title: "no. 9, op. 125, D minor (Choral)" },
          ],
        },
        {
          composer: {
            name: "Brahms",
          },
          composition: {
            name: "Concerto",
          },
          songs: [
            { title: "Piano and Orchestra, no. 1, op. 15, D minor" },
            { title: "Piano and Orchestra, no. 2. op. 83, B flat major" },
            { title: "Violin and Orchestra, op. 77, D major" },
            { title: "Violin, Cello and Orchestra, op.102, A minor" },
          ],
        },
        {
          composer: {
            name: "Brahms",
          },
          composition: {
            name: "Overture",
          },
          songs: [
            { title: "Overture, op. 80, C minor (Academic Festival Overture)" },
            { title: "Overture, op. 81, D minor (Tragic Overture)" },
          ],
        },
        {
          composer: {
            name: "Brahms",
          },
          composition: {
            name: "Symphony",
          },
          songs: [
            { title: "no. 1, op. 68, C minor" },
            { title: "no. 2, op. 73, D major" },
            { title: "no. 3, op. 90, F major" },
            { title: "no. 4, op. 98, E minor" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Ballade",
          },
          songs: [
            { title: "no. 1, op. 23, G minor" },
            { title: "no. 2, op. 38, F major" },
            { title: "no. 3, op. 47, A flat major" },
            { title: "no. 4, op. 52, F minor" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Barcarolle",
          },
          songs: [
            { title: "op. 60, F sharp major" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Berceuse",
          },
          songs: [
            { title: "op. 57, D flat major" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Concerto",
          },
          songs: [
            { title: "Piano no. 1, op. 11, E minor" },
            { title: "Piano no. 2, op. 21, F minor" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Etude",
          },
          songs: [
            { title: "no. 1, op. 10, no. 1, C major" },
            { title: "no. 2, op. 10, no. 2, A minor" },
            { title: "no. 3, op. 10, no. 3, E major" },
            { title: "no. 4, op. 10, no. 4, C sharp minor" },
            { title: "no. 5, op. 10, no. 5, G flat major" },
            { title: "no. 6, op. 10, no. 6, E flat minor" },
            { title: "no. 7, op. 10, no. 7, C major" },
            { title: "no. 8, op. 10, no. 8, F major" },
            { title: "no. 9, op. 10, no. 9, F minor" },
            { title: "no. 10, op. 10, no. 10, A flat major" },
            { title: "no. 11, op. 10, no. 11, E flat major" },
            { title: "no. 12, op. 10, no. 12, C minor" },
            { title: "no. 13, op. 25, no. 1, A flat major" },
            { title: "no. 14, op. 25, no. 2, F minor" },
            { title: "no. 15, op. 25, no. 3, F major" },
            { title: "no. 16, op. 25, no. 4, A minor" },
            { title: "no. 17, op. 25, no. 5, E minor" },
            { title: "no. 18, op. 25, no. 6, G sharp minor" },
            { title: "no. 19, op. 25, no. 7, C sharp minor" },
            { title: "no. 20, op. 25, no. 8, D flat major" },
            { title: "no. 21, op. 25, no. 9, G flat major" },
            { title: "no. 22, op. 25, no. 10, B minor" },
            { title: "no. 23, op. 25, no. 11, A minor" },
            { title: "no. 24, op. 25, no. 12, C minor" },
            { title: "no. 25, op. posth., no. 1, F minor" },
            { title: "no. 26, op. posth., no. 2, A flat major" },
            { title: "no. 27, op. posth., no. 3, D flat major" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Fantasia",
          },
          songs: [
            { title: "op. 49, F minor" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Impromptu",
          },
          songs: [
            { title: "no. 1, op. 29, A flat major" },
            { title: "no. 2, op. 36, F sharp major" },
            { title: "no. 3, op. 51, G flat major" },
            { title: "no. 4, op. 66, C sharp minor (Fantaisie Impromptu)" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Mazurka",
          },
          songs: [
            { title: "no. 1, op. 6, no. 1, F sharp minor" },
            { title: "no. 2, op. 6, no. 2, C sharp minor" },
            { title: "no. 3, op. 6, no. 3, E major" },
            { title: "no. 4, op. 6, no. 4, E flat minor" },
            { title: "no. 5, op. 7, no. 1, B flat major" },
            { title: "no. 6, op. 7, no. 2, A minor" },
            { title: "no. 7, op. 7, no. 3, F minor" },
            { title: "no. 8, op. 7, no. 4, A flat major" },
            { title: "no. 9, op. 7, no. 5, C major" },
            { title: "no. 10, op. 17, no. 1, B flat major" },
            { title: "no. 11, op. 17, no. 2, E minor" },
            { title: "no. 12, op. 17, no. 3, A flat major" },
            { title: "no. 13, op. 17, no. 4, A minor" },
            { title: "no. 14, op. 24, no. 1, G minor" },
            { title: "no. 15, op. 24, no. 2, C major" },
            { title: "no. 16, op. 24, no. 3, A flat major" },
            { title: "no. 17, op. 24, no. 4, B flat minor" },
            { title: "no. 18, op. 30, no. 1, C minor" },
            { title: "no. 19, op. 30, no. 2, B minor" },
            { title: "no. 20, op. 30, no. 3, D flat major" },
            { title: "no. 21, op. 30, no. 4, C sharp minor" },
            { title: "no. 22, op. 33, no. 1, G sharp minor" },
            { title: "no. 23, op. 33, no. 2, D major" },
            { title: "no. 24, op. 33, no. 3, C major" },
            { title: "no. 25, op. 33, no. 4, B minor" },
            { title: "no. 25, op.33, no. 4, B minor" },
            { title: "no. 26, op. 41, no. 1, C sharp minor" },
            { title: "no. 27, op. 41, no. 2, B major" },
            { title: "no. 28, op. 41, no. 3, B major" },
            { title: "no. 29, op. 41, no. 4, A flat major" },
            { title: "no. 29, op. 41, no. 4, C sharp minor" },
            { title: "no. 30, op. 50, no. 1, G major" },
            { title: "no. 31, op. 50, no. 2, A flat major" },
            { title: "no. 32, op. 50, no. 3, C sharp minor" },
            { title: "no. 33, op. 56, no. 1, B major" },
            { title: "no. 34, op. 56, no. 2, C major" },
            { title: "no. 35, op. 56, no. 3, C minor" },
            { title: "no. 36, op. 59, no. 1, A minor" },
            { title: "no. 37, op. 59, no. 2, A flat major" },
            { title: "no. 38, op. 59, no. 3, F sharp minor" },
            { title: "no. 39, op. 63, no. 1, B major" },
            { title: "no. 40, op. 63, no. 2, F minor" },
            { title: "no. 41, op. 63, no. 3, C sharp minor" },
            { title: "no. 42, op. 67 (posth.), no. 1, G major" },
            { title: "no. 43, op. 67 (posth.), no. 2, G minor" },
            { title: "no. 44, op. 67 (posth.), no. 3, C major" },
            { title: "no. 45, op. 67 (posth.), no. 4, A minor" },
            { title: "no. 46, op. 68 (posth.), no. 1, C major" },
            { title: "no. 47, op. 68 (posth.), no. 2, A minor" },
            { title: "no. 48, op. 68 (posth.), no. 3, F major" },
            { title: "no. 49, op. 68 (posth.), no. 4, F minor" },
            { title: "no. 50, A minor (Notre Temps)" },
            { title: "no. 51, A minor" },
            { title: "no. 52, op. posth., no. 2, B flat major" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Nocturne",
          },
          songs: [
            { title: "no. 1, op. 9, no. 1, B flat minor" },
            { title: "no. 2, op. 9, no. 2, E flat major" },
            { title: "no. 3, op. 9, no. 3, B major" },
            { title: "no. 4, op. 15, no. 1, F major" },
            { title: "no. 5, op. 15, no. 2, F sharp major" },
            { title: "no. 6, op. 15, no. 3, G minor" },
            { title: "no. 7, op. 27, no. 1, C sharp minor" },
            { title: "no. 8, op. 27, no. 2, D flat major" },
            { title: "no. 9, op. 32, no. 1, B major" },
            { title: "no. 10, op. 32, no. 2, A flat major" },
            { title: "no. 11, op. 37, no. 1, G minor" },
            { title: "no. 12, op. 37, no. 2, G major" },
            { title: "no. 13, op. 48, no. 1, C minor" },
            { title: "no. 14, op. 48, no. 2, F sharp minor" },
            { title: "no. 15, op. 55, no. 1, F minor" },
            { title: "no. 16, op. 55, no. 2, E flat major" },
            { title: "no. 17, op. 62, no. 1, B major" },
            { title: "no. 18, op. 62, no. 2, E major" },
            { title: "no. 19, op. 72, no. 1, E minor" },
            { title: "no. 20, op. posth., no. 1, C sharp minor" },
            { title: "no. 21, op. posth., C minor" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Polonaise",
          },
          songs: [
            { title: "Andante Spianato and Grande Polonaise Brillante, op. 22, E flat major" },
            { title: "no. 1, op. 26, no. 1, C sharp minor" },
            { title: "no. 2, op. 26, no. 2, E flat minor" },
            { title: "no. 3, op. 40, no. 1, A major (Militaire)" },
            { title: "no. 4, op. 40, no. 2, C minor" },
            { title: "no. 5, op. 44, F sharp minor" },
            { title: "no. 6, op. 53, A flat major (Heroic)" },
            { title: "no. 7, op. 61, A flat major" },
            { title: "no. 8, op. 71, no. 1, D minor" },
            { title: "no. 9, op. 71, no. 2, B flat major" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Prelude",
          },
          songs: [
            { title: "no. 1, op. 28, no. 1, C major" },
            { title: "no. 2, op. 28, no. 2, A minor" },
            { title: "no. 3, op. 28, no. 3, G major" },
            { title: "no. 4, op. 28, no. 4, E minor" },
            { title: "no. 5, op. 28, no. 5, D major" },
            { title: "no. 6, op. 28, no. 6, B minor" },
            { title: "no. 7, op. 28, no. 7, A major" },
            { title: "No. 8, op. 28, no. 8, F sharp minor" },
            { title: "no. 9, op. 28, no. 9, E major" },
            { title: "no. 10, op. 28, no. 10, C sharp minor" },
            { title: "no. 11, op. 28, no. 11, B major" },
            { title: "no. 12, op. 28, no. 12, G sharp minor" },
            { title: "no. 13, op. 28, no. 13, F sharp major" },
            { title: "no. 14, op. 28, no. 14, E flat minor" },
            { title: "no. 15, op. 28, no. 15, D flat major" },
            { title: "no. 16, op. 28, no. 16, B flat minor" },
            { title: "no. 17, op. 28, no. 17, A flat major" },
            { title: "no. 18, op. 28, no. 18, F minor" },
            { title: "no. 19, op. 28, no. 19, E flat major" },
            { title: "no. 20, op. 28, no. 20, C minor" },
            { title: "no. 21, op. 28, no. 21, B flat major" },
            { title: "no. 22, op. 28, no. 22, G minor" },
            { title: "no. 23, op. 28, no. 23, F major" },
            { title: "no. 24, op. 28, no. 24, D minor" },
            { title: "no. 25, op. 45, C sharp major" },
            { title: "no. 26, op. posth., A flat major" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Rondo",
          },
          songs: [
            { title: "two pianos, Op. 73 (posth.), C major" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Scherzo",
          },
          songs: [
            { title: "no. 1, op. 20, B minor" },
            { title: "no. 2, op. 31, B flat minor" },
            { title: "no. 3, op. 39, C sharp minor" },
            { title: "no. 4, op. 54, E major" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Sonata",
          },
          songs: [
            { title: "no. 2, op. 35, B flat minor" },
            { title: "no. 3, op. 58, B minor" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Tarantella",
          },
          songs: [
            { title: "Tarantelle, op. 43, A flat major" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Variation",
          },
          songs: [
            { title: "on a German air" },
            { title: "on 'Là ci darem la mano', op.2" },
            { title: "no. 2, op. 12 (Variations Brillantes)" },
          ],
        },
        {
          composer: {
            name: "Chopin",
          },
          composition: {
            name: "Waltze",
          },
          songs: [
            { title: "no. 1, op. 18, E flat major" },
            { title: "no. 2, op. 34, no. 1, A flat major" },
            { title: "no. 3, op. 34, no. 2, A minor" },
            { title: "no. 4, op. 34, no. 3, F major" },
            { title: "no. 5, op. 42, A flat major" },
            { title: "no. 6, op. 64, no. 1, D flat major" },
            { title: "no. 7, op. 64, no. 2, C sharp minor" },
            { title: "no. 8, op. 64, no. 3, A flat major" },
            { title: "no. 9, op. 69, no. 1, A flat major" },
            { title: "no. 10, op. 69, no. 2, B minor" },
            { title: "no. 11, op. 70, no. 1, G flat major" },
            { title: "no. 12, op. 70, no. 2, F minor" },
            { title: "no. 13, op. 70, no. 3, D flat major" },
            { title: "no. 14, op. posth., E minor" },
          ],
        },
        {
          composer: {
            name: "Liszt",
          },
          composition: {
            name: "Etude",
          },
          songs: [
            { title: "Concert Etude no. 1" },
            { title: "Concert Etude no. 2" },
            { title: "Concert Etude no. 3" },
            { title: "Grande etude de perfectionnement" },
            { title: "Grandes etudes de Paganini no. 1, G minor" },
            { title: "Grandes etudes de Paganini no. 2, E flat major" },
            { title: "Grandes etudes de Paganini no. 3, A flat minor" },
            { title: "Grandes etudes de Paganini no. 4, E major" },
            { title: "Grandes etudes de Paganini no. 5, E major" },
            { title: "Grandes etudes de Paganini no. 6, A minor" },
            { title: "Transcendental Étude No. 1 (Preludio)	C major" },
            { title: "Transcendental Étude No. 2 (Fusées)	A minor" },
            { title: "Transcendental Étude No. 3 (Paysage)	F major" },
            { title: "Transcendental Étude No. 4 (Mazeppa)	D minor" },
            { title: "Transcendental Étude No. 5 (Feux follets)	B flat major" },
            { title: "Transcendental Étude No. 6 (Vision)	G minor" },
            { title: "Transcendental Étude No. 7 (Eroica)	E flat major" },
            { title: "Transcendental Étude No. 8 (Wilde Jagd)	C minor" },
            { title: "Transcendental Étude No. 9 (Ricordanza)	A flat major" },
            { title: "Transcendental Étude No. 10 (Appassionata)	F minor" },
            { title: "Transcendental Étude No. 11 (Harmonies du soir)	D flat major" },
            { title: "Transcendental Étude No. 12 (Chasse-neige)	B flat minor" },
          ],
        },
        {
          composer: {
            name: "Liszt",
          },
          composition: {
            name: "Concerto",
          },
          songs: [
            { title: "pathétique" },
            { title: "Piano No. 1, E flat major" },
            { title: "Piano No. 2, A major" },
            { title: "Piano No. 3, E flat major" },
          ],
        },
        {
          composer: {
            name: "Liszt",
          },
          composition: {
            name: "Hungarian Rhapsodie",
          },
          songs: [
            { title: "No. 1	C sharp minoraisies" },
            { title: "No. 2	C sharp minor" },
            { title: "No. 3	B flat major" },
            { title: "No. 4	E flat major" },
            { title: "No. 5	E minor" },
            { title: "No. 6	D flat major" },
            { title: "No. 7	D minor" },
            { title: "No. 8	F sharp minor	" },
            { title: "No. 9	E flat major" },
            { title: "No. 10 E major" },
            { title: "No. 11 A minor" },
            { title: "No. 12 C sharp minor" },
            { title: "No. 13 A minor" },
            { title: "No. 14 F minor" },
            { title: "No. 15 A minor" },
            { title: "No. 16 A minor" },
            { title: "No. 17 D minor" },
            { title: "No. 18 F sharp minor" },
            { title: "No. 19 D minor" },
          ],
        },
        {
          composer: {
            name: "Liszt",
          },
          composition: {
            name: "Symphonic poem",
          },
          songs: [
            { title: "No. 1 Ce qu'on entend sur la montagne" },
            { title: "No. 2 Tasso: lamento e trionfo" },
            { title: "No. 3 Les préludes" },
            { title: "No. 4 Orph" },
            { title: "No. 5 Prometheus" },
            { title: "No. 6 Mazeppa" },
            { title: "No. 7 Festklänge" },
            { title: "No. 8 Héroïde funèbre" },
            { title: "No. 9 Hungaria" },
            { title: "No. 10 Hamlet" },
            { title: "No. 11 Hunnenschlacht" },
            { title: "No. 12 Die Ideale" },
            { title: "No. 13 Von der Wiege bis zum Grabe" },
          ],
        },
        {
          composer: {
            name: "Haydn",
          },
          composition: {
            name: "Symphonie",
          },
          songs: [
            { title: "C major (Toy Symphony)" },
            { title: "no. 1, D major" },
            { title: "no. 6, G Major" },
            { title: "no. 7, C major (Le Midi)" },
            { title: "no. 8, G major (Le Soir)" },
            { title: "no. 13, D major" },
            { title: "no. 22, E flat major (Philosopher)" },
            { title: "no. 26, D minor (Lamentatione)" },
            { title: "no. 27, G major (Bruckenthal)" },
            { title: "no. 28, A major" },
            { title: "no. 31, D major (Hornsignal)" },
            { title: "no. 34, D minor" },
            { title: "no. 35, B flat major" },
            { title: "no. 36, E flat major" },
            { title: "no. 40, F major" },
            { title: "no. 43, E flat major" },
            { title: "no. 44, E minor (Trauersymphonie)" },
            { title: "no. 45, F sharp minor (Farewell)" },
            { title: "no. 48, C major (Marie Teresa)" },
            { title: "no. 49, F minor (La Passione)" },
            { title: "no. 50, C major" },
            { title: "no. 53, D major (Imperiale)" },
            { title: "no. 54, G major" },
            { title: "no. 64, A major" },
            { title: "no. 67, F major" },
            { title: "no. 70, D major" },
            { title: "no. 73, op. 34, D major (La Chasse)" },
            { title: "no. 80, op. 39, D minor" },
            { title: "no. 83, G minor (The Hen)" },
            { title: "no. 85, B flat major (The Queen)" },
            { title: "no. 86, op. 52, no. 2, D major" },
            { title: "no. 88, op. 56, no. 2, G major" },
            { title: "no. 90, op. 66, no. 1, C major" },
            { title: "no. 91, op. 66, no. 3, E flat major" },
            { title: "no. 92, op. 66, no. 2, G major (Oxford)" },
            { title: "no. 93, op. 83, no. 2, D major" },
            { title: "no. 94, op. 80, no. 1, G major (Surprise)" },
            { title: "no. 95, op. 77, no. 1, C minor" },
            { title: "no. 96, op. 77, no. 2, D major (The Miracle)" },
            { title: "no. 97, op. 83, no. 1, C major" },
            { title: "no. 98, op. 82, no. 2, B flat major" },
            { title: "no. 99, op. 98, no. 3, E flat major" },
            { title: "no. 100, op. 90, G major (Military)" },
            { title: "no. 101, op. 95, no. 2, D major (Clock)" },
            { title: "no. 102, op. 98, no. 2, B flat major" },
            { title: "no. 103, op. 95, no. 1, E flat major (Drum Roll)" },
            { title: "no. 104, op. 98, no. 1, D major (London)" },
          ],
        },
        {
          composer: {
            name: "Mozart",
          },
          composition: {
            name: "Concerto",
          },
          songs: [
            { title: "Two Pianos and Orchestra, k. 242, F major" },
            { title: "Two Pianos and Orchestra, k. 365, E flat major" },
            { title: "Violin and Orchestra KV.218" },
            { title: "Piano and Orchestra no. 1, k. 37, F major" },
            { title: "Piano and Orchestra no. 2, k. 39, B flat major" },
            { title: "Piano and Orchestra no. 5, k. 175, D major" },
            { title: "Piano and Orchestra no. 6, k. 238, B flat major" },
            { title: "Piano and Orchestra no. 8, k. 246, C major" },
            { title: "Piano and Orchestra no. 9, k. 271, E flat major" },
            { title: "Piano and Orchestra no. 11, k. 413, F major" },
            { title: "Piano and Orchestra no. 12, k. 414, A major" },
            { title: "Piano and Orchestra no. 13, k. 415, C major" },
            { title: "Piano and Orchestra no. 14, k. 449, E flat major" },
            { title: "Piano and Orchestra no. 15, k. 450, B flat major" },
            { title: "Piano and Orchestra no. 17, k. 453, G major" },
            { title: "Piano and Orchestra no. 18, k. 456, B flat major" },
            { title: "Piano and Orchestra no. 19, k. 459, F major" },
            { title: "Piano and Orchestra no. 20, k. 466, D minor" },
            { title: "Piano and Orchestra no. 21, k. 467, C major" },
            { title: "Piano and Orchestra no. 22, k. 482, E flat major" },
            { title: "Piano and Orchestra no. 23, k. 488, A major" },
            { title: "Piano and Orchestra no. 24, k. 491, C minor" },
            { title: "Piano and Orchestra no. 25, k. 503, C major" },
            { title: "Piano and Orchestra no. 26, k. 537, D major" },
            { title: "Piano and Orchestra no. 27, k. 595, B flat major" },
          ],
        },
        {
          composer: {
            name: "Mozart",
          },
          composition: {
            name: "Symphonie",
          },
          songs: [
            { title: "concertante k. 364" },
            { title: "no. 1, k. 16, E flat major" },
            { title: "no. 4, k. 19, D major" },
            { title: "no. 5, k. 22, B flat major" },
            { title: "no. 6, k. 43, F major" },
            { title: "no. 7, k. 45, D major" },
            { title: "no. 8, k. 48, D major" },
            { title: "no. 9, k. 73, C major" },
            { title: "no. 10, k. 74, G major" },
            { title: "no. 11, k. 84, D major" },
            { title: "no. 12, k. 110, G major" },
            { title: "no. 14, k. 114, A major" },
            { title: "no. 18, k. 130, F major" },
            { title: "no. 19, k. 132, E flat major" },
            { title: "no. 20, k. 133, D major" },
            { title: "no. 21, k. 134, A major" },
            { title: "no. 22, k. 162, C major" },
            { title: "no. 23, k. 181, D major" },
            { title: "no. 24, k. 182, B major" },
            { title: "no. 25, k. 183, G minor" },
            { title: "no. 26, k. 184, E flat major" },
            { title: "no. 27, k. 199, G major" },
            { title: "no. 28, k. 200, C major" },
            { title: "no. 29, k. 201, A major" },
            { title: "no. 30, k. 202, D major" },
            { title: "no. 31, k. 297, D major (Paris)" },
            { title: "no. 32, k. 318, G major" },
            { title: "no. 33, k. 319, B flat major" },
            { title: "no. 34, k. 338, C major" },
            { title: "no. 35, k. 385, D major (Haffner)" },
            { title: "no. 36, k. 425, C major (Linz)" },
            { title: "no. 38, k. 504, D major (Prague)" },
            { title: "no. 39, k. 543, E flat major" },
            { title: "no. 40, k. 550, G minor" },
            { title: "no. 41, k. 551, C major (Jupiter)" },
          ],
        },
        {
          composer: {
            name: "Mozart",
          },
          composition: {
            name: "Ballet",
          },
          songs: [
            { title: "Les petits riens" },
          ],
        },
        {
          composer: {
            name: "Mozart",
          },
          composition: {
            name: "Mass",
          },
          songs: [
            { title: "Coronation Mass" },
            { title: "Great Mass in C minor, K. 427" },
            { title: "Great Mass in C minor, K. 427 (Leonard Bernstein film)" },
            { title: "Kyrie in D minor, K. 341" },
            { title: "Kyrie in F major, K. 33" },
            { title: "Mass in B-flat major, K. 275" },
            { title: "Mass in C major, K. 66 Dominicus" },
            { title: "Mass in C major, K. 167 in honorem Sanctissimae Trinitatis" },
            { title: "Mass in C major, K. 220 Sparrow" },
            { title: "Mass in C major, K. 257 Credo" },
            { title: "Mass in C major, K. 258 Piccolomini" },
            { title: "Mass in C major, K. 259 Organ solo" },
            { title: "Mass in C major, K. 262 Missa longa" },
            { title: "Mass in C major, K. 337 Solemnis" },
            { title: "Mass in C minor, K. 139 Waisenhaus" },
            { title: "Mass in D major, K. 194" },
            { title: "Mass in D minor, K. 65" },
            { title: "Mass in F major, K. 192" },
            { title: "Mass in G major, K. 49" },
            { title: "Mass in G major, K. 140 Pastoral" },
            { title: "Requiem" },
          ],
        },
        {
          composer: {
            name: "Mozart",
          },
          composition: {
            name: "Sonata",
          },
          songs: [
            { title: "Piano No. 1" },
            { title: "Piano No. 2" },
            { title: "Piano No. 3" },
            { title: "Piano No. 4" },
            { title: "Piano No. 5" },
            { title: "Piano No. 6" },
            { title: "Piano No. 7" },
            { title: "Piano No. 8" },
            { title: "Piano No. 9" },
            { title: "Piano No. 10" },
            { title: "Piano No. 11" },
            { title: "Piano No. 12" },
            { title: "Piano No. 13" },
            { title: "Piano No. 14" },
            { title: "Piano No. 15" },
            { title: "Piano No. 16" },
            { title: "Piano No. 17" },
            { title: "Piano No. 18" },
            { title: "Piano in B-flat major, K. 498a" },
            { title: "Piano in F major, K. 547a" },
            { title: "Two Pianos in D major" },
            { title: "Piano four hands in C major, K. 521" },
            { title: "Violin KV 6" },
            { title: "Violin KV 7" },
            { title: "Violin KV 8" },
            { title: "Violin KV 9" },
            { title: "Violin KV 10" },
            { title: "Violin KV 11" },
            { title: "Violin KV 12" },
            { title: "Violin KV 13" },
            { title: "Violin KV 14" },
            { title: "Violin KV 15" },
            { title: "Violin No. 23" },
            { title: "Violin No. 24" },
            { title: "Violin KV 26" },
            { title: "Violin KV 27" },
            { title: "Violin KV 28" },
            { title: "Violin KV 29" },
            { title: "Violin KV 30" },
            { title: "Violin KV 31" },
            { title: "Violin No. 17" },
            { title: "Violin No. 18" },
            { title: "Violin No. 19" },
            { title: "Violin No. 20" },
            { title: "Violin No. 21" },
            { title: "Violin No. 22" },
            { title: "Violin No. 27" },
            { title: "Violin No. 32" },
            { title: "Violin No. 33" },
            { title: "Violin No. 35" },
            { title: "Violin No. 36" },
            { title: "Fantasia No. 2" },
            { title: "Violin Sonata in D major" },
          ],
        },
        {
          composer: {
            name: "String quintet",
          },
          composition: {
            name: "Symphonie",
          },
          songs: [
            { title: "No. 1" },
            { title: "No. 2" },
            { title: "No. 3" },
            { title: "No. 4" },
            { title: "No. 5" },
            { title: "No. 6" },
          ],
        },
      ]
    end
  end
end
